export const FECTH_API_START = 'FETCH_API_START';
export const FETCH_API_NEXT_PAGE_START = 'FETCH_API_NEXT_PAGE_START';
export const FETCH_API_NEXT_PAGE_SUCCESS = 'FETCH_API_NEXT_PAGE_SUCCESS';
export const FECTH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FECTH_API_FAILURE = 'FETCH_API_FAILURE';
